// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMRRmyOi22WvHtzOxp68yjmezFIgWIpOw',
    appId: '1:1053062087313:web:cd04ace477dbadbcbef530',
    messagingSenderId: '1053062087313',
    projectId: 'localizationapp-55c5c',
    authDomain: 'localizationapp-55c5c.firebaseapp.com',
    storageBucket: 'localizationapp-55c5c.appspot.com',
    measurementId: 'G-GV9GETGR0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEIsrERlYJx1yp66yWf1yFl1HWK6KUVsc',
    appId: '1:1053062087313:android:beede3c0a4ad3be4bef530',
    messagingSenderId: '1053062087313',
    projectId: 'localizationapp-55c5c',
    storageBucket: 'localizationapp-55c5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Ec3cVXxVnGdAkJHj9ggsWFhI-bpA39I',
    appId: '1:1053062087313:ios:c12dd60d4edd7a4fbef530',
    messagingSenderId: '1053062087313',
    projectId: 'localizationapp-55c5c',
    storageBucket: 'localizationapp-55c5c.appspot.com',
    iosClientId: '1053062087313-6q7beqhukm3i3vdre25l4tji04bb53dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.localizationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Ec3cVXxVnGdAkJHj9ggsWFhI-bpA39I',
    appId: '1:1053062087313:ios:c12dd60d4edd7a4fbef530',
    messagingSenderId: '1053062087313',
    projectId: 'localizationapp-55c5c',
    storageBucket: 'localizationapp-55c5c.appspot.com',
    iosClientId: '1053062087313-6q7beqhukm3i3vdre25l4tji04bb53dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.localizationapp',
  );
}
